### ISSUE TITLE
[WIP] Themes and Layouts

### ISSUE THREAD

**Issue by tristanlins** [avisota/contao-core#147]
@Incomplete

Wir haben uns bereits entschieden, die [Mail Template Vorlagen](https://github.com/mailchimp/email-blueprints) die von Mailchimp unter der CC-BY-SA-3.0-Unported bereitgestellt werden als neues Grundgerüst zu nutzen.

@see [Types of Email](http://templates.mailchimp.com/concepts/types-of-email/)
@see [Layout and Purpose](http://templates.mailchimp.com/design/layout-and-purpose/)
## Todos
- [ ] "Theme" in "Layout" ändern.
- [ ] Themes wie in Contao einführen.
- [ ] Berechtigungen auf Themes und Layouts
## Themes und Layouts

Bisher wurde der Begriff Theme für ein Newsletterdesign verwendet, das ist aber in Bezug auf die in Contao bekannte Begrifflichkeit unpassend und führt nur zu Verwirrung. Statt dessen soll die bisherige Implementierung der "Themes" in "Layouts" geändert werden und zusätzlich Themes wie in Contao bekannt eingeführt werden.
Das ermöglicht später den Ex- und Import von Themes bzw. die einfachere Pflege unterschiedlicher Layouts.

Ein Theme definiert
- das Template Verzeichnis

Ein Layout definiert
- welches Basistemplate verwendet wird
- welche Struktur (Anzahl Zeilen/Spalten, sowie deren Anordnung) der Newsletter hat
- welche Inhaltselemente in welcher Zelle erlaubt sind
- welche CSS Dateien verwendet werden
## Templates

Als Basistemplates werden die [Mail Template Vorlagen](https://github.com/mailchimp/email-blueprints) von Mailchimp verwendet.
Um eine saubere Updatefähigkeit zu erhalten, werden die Temlates aber nicht angepasst.
Statt dessen werden die Templates mit Hilfe eines DomDocument+XPath basierenden Parsers verarbeitet.
Wie dieser Parse konfiguriert wird und arbeitet wird in den kommenden Abschnitten beschrieben. 
### Aufbau und Anordnung von Inhalten

Im Gegensatz zu Contao's "einfachem" Ansatz von _Kopfzeile, linke Spalte, Hauptspalte, rechte Spalte, Fußzeile_ bieten die Mailchimp Templates deutlich komplexere Strukturen an.
Eine dynamischen Konfiguration dieser Strukturen sehen wir als nicht sinngemäß, da diese immer auch vom Basistemplate abhängig sind.
Statt dessen streben wir eine Konfiguration auf PHP Ebene an, diese könnte bspw. so aussehen:
#### Non-Responsive Layout

``` php
$struct['col3_news'] = array(
    // Name des zu verwendenden Basistemplates
    'template' => '3col-basic3column.html',

    // Eigenschaften (Widgets) die dieser Vorlage zugewiesen werden und pro Theme definiert werden können
    'properties' => array(
        'width' => array(
            'inputType' => 'text',
            'default' => 600,
            'eval' => array('rgxp' => 'digit'),
        ),
        'headerImage' => array(
            'inputType' => 'fileTree',
            'eval' => array('files' => true, 'filesOnly' => true, 'extensions' => 'jpg,png,gif', 'fieldType' => 'radio')
        ),
    ),

    // Basisdefinition der Zellen und derer Inhalte
    'cells' => array(
        'title' => array(
            'xpath' => '//meta[@property="og:title"]/@content|',
            // fixed content for this cell
            'content' => '##newsletter.subject##',
        ),
        'teaser' => array(
            // xpath to select the element, the content will be injected into
            'xpath' => '//div[@mc:edit="std_preheader_content"]',
            // if there is no content, remove this target element, instead of the xpath element
            'ifEmptyRemove' => '//div[@mc:edit="std_preheader_content"]/..', // <-- this would remove the <td>
        ),
        'viewonline' => array(
            'xpath' => '//div[@mc:edit="std_preheader_links"]',
            'content' => '##view_online_link##',
        ),
        'header' => array(
            'xpath' => '//table[@id="templateContainer"]//img[@id="headerImage"]',
            // fixed content for this cell
            'content' => '{{image::##theme.headerImage##}}',
        ),
        'col1' => array(
            'xpath' => '//div[@id="templateBody"]//td[@class="leftColumnContent"]',
            // wrap the complete content for this cell with:
            'wrapContent' => '<table border="0" cellpadding="20" cellspacing="0" width="100%"></table>',
            // wrap each row/element with:
            'wrapRow' => '<tr><td valign="top"></td></tr>',
        ),
        // Spalte 2:
        'col2' => array(
            'xpath' => '//table[@id="templateBody"]//td[@class="centerColumnContent"]',
            // wrap the complete content for this cell with:
            'wrapContent' => '<table border="0" cellpadding="20" cellspacing="0" width="100%"></table>',
            // wrap each row/element with:
            'wrapRow' => '<tr><td valign="top"></td></tr>',
        ),
        // Spalte 3:
        'col3' => array(
            'xpath' => '//table[@id="templateBody"]//td[@class="rightColumnContent"]',
            // wrap the complete content for this cell with:
            'wrapContent' => '<table border="0" cellpadding="20" cellspacing="0" width="100%"></table>',
            // wrap each row/element with:
            'wrapRow' => '<tr><td valign="top"></td></tr>',
        )
        'news' => array(
            'xpath' => '//table[@id="templateContainer"]//div[@id="headerImage"]',
            // Anstatt den Inhalt zu ersetzen, soll das selektierte Element vollständig ersetzt werden
            'replace' => true,
            // Elementtypen die für diese Zelle vorgesehen sind,
            // solange der Administrator die Liste der für diese Spalte erlaubten Inhaltselemente nicht überschreibt
            // kann ein Redakteur nur diese Elemente auswählen
            'preferedElements' => array('news', 'event')
        )
        'footer' => array(
            'xpath' => '//table[@id="templateFooter"]//td[@class="footerContent"]',
        ),
    ),

    // Formatierung und Anordnung der Zellen im Bearbeitungsmodus
    'formation' => array(
        // Zeile 1:
        array(
            // Spalte 1-3;
            'teaser' => array('colspan' => 3),
        ),
        // Zeile 2:
        array(
            // Spalte 1;
            'col1' => array(),
            // Spalte 2;
            'col2' => array(),
            // Spalte 3;
            'col3' => array(),
        ),
        // Zeile 3:
        array(
            // Spalte 1-3;
            'news' => array('colspan' => 3),
        ),
        // Zeile 4:
        array(
            // Spalte 1-3;
            'footer' => array('colspan' => 3),
        ),
    )
)
```
#### Responsive Layout

``` php
$struct['col3_responsive'] = array(
    'template' => 'base_boxed_3column_query.html',

    'properties' => array(
        ...
    ),

    // Basisdefinition der Zellen und derer Inhalte
    'cells' => array(
        ...
        'col1' => array(
            // Diese Zelle gehört zu einer repeatable Zeile, hier ist auf den Platzhalter {index}
            // und auf den Index für die Spalte zu achten!
            //                                             !        !
            //                                             V        V
            'xpath' => '//div[@id="templateColumns"]/tr[{index}]/td[1][@class="templateColumnContainer"]',
            'wrapContent' => '<table border="0" cellpadding="20" cellspacing="0" width="100%"></table>',
            'wrapRow' => '<tr><td class="leftColumnContent"></td></tr>',
        ),
        // Spalte 2:
        'col2' => array(
            //                                             !        !
            //                                             V        V
            'xpath' => '//div[@id="templateColumns"]/tr[{index}]/td[2][@class="templateColumnContainer"]',
            'wrapContent' => '<table border="0" cellpadding="20" cellspacing="0" width="100%"></table>',
            'wrapRow' => '<tr><td class="centerColumnContent"></td></tr>',
        ),
        // Spalte 3:
        'col3' => array(
            //                                             !        !
            //                                             V        V
            'xpath' => '//div[@id="templateColumns"]/tr[{index}]/td[3][@class="templateColumnContainer"]',
            'wrapContent' => '<table border="0" cellpadding="20" cellspacing="0" width="100%"></table>',
            'wrapRow' => '<tr><td class="rightColumnContent"></td></tr>',
        )
        ...
    ),

    // Wenn Zeilen repeatable sind, müssen diese separat angegeben werden
    'rows' => array(
        // Jede Zeile bekommt einen eindeutigen Namen,
        // dieser dient vorwiegend der Identifikation im Wireframe
        'repeatable-row-2' => array(
            // Selector auf das zu wiederholende Element
            'xpath' => '//div[@id="templateColumns"]/tr[@mc:repeatable]',
            // Liste aller Zellen die betroffen sind, dies ist notwendig damit
            // es später möglich ist, die Anzahl Wiederholungen zu ermitteln
            'affectedCells' => array('col1', 'col2', 'col3')
        )
    ),

    // Formatierung und Anordnung der Zellen im Bearbeitungsmodus
    'formation' => array(
        ...
        // Zeile 2:
        // damit das Wireframe die Zeile als repeatable erkennt, muss der Key
        // identisch mit der Konfiguration in "rows" sein.
        'repeatable-row-2' => array(
            // Spalte 1;
            'col1' => array(),
            // Spalte 2;
            'col2' => array(),
            // Spalte 3;
            'col3' => array(),
        ),
        ...
    )
)
```
### Parsen und Rendern von Mails

Das Parsen und Rendern übernimmt ein DomDocument+XPath basierendes System.
Das Template wird als DomDocument geladen.
Mit Hilfe von XPath Ausdrücken, werden anschließend Teile des Templates dynamisch angepasst und ersetzt.
Welche Elemente mit welchen Inhalten befüllt werden wird über die `cells` Konfiguration bestimmt.

Der gesamte Verarbeitungsvorgang läuft wie folgt ab:
- Elemente rendern
- Elemente in Basis-Template einfügen
- Simple Tokens in Basis-Template ersetzen
- Insert Tags in Basis-Template ersetzen
- -> fertige E-Mail
## Bearbeiten von Inhalten

Die `formation` Konfiguration hat keinen Einfluss auf das Rendering der Mail.
Diese dient dazu, die Backendansicht auf Basis des DC_General so anzupassen, dass der Strukturelle Aufbau bereits in der Bearbeitungsmaske abgebildet ist.
Anstelle einer einfachen Listenansicht, wie sie in Contao bekannt ist, wird eine strukturierte Ansicht gezeigt, aus der ein Redakteur gleich den Aufbau des Inhaltes ableiten kann.
### Aktueller Entwurf

Anstelle einer vollständigen Bearbeitungsmaske wird ein Wireframe angezeigt, aus dem der Redakteur die Zelle wählen kann die er bearbeiten will.

```
  ----------------------------------------------------------------------------
  |                                                                          |
  |  Kopfzeile                                                               |
  |  * Text                                                                  |
  |                                                                          |
  ----------------------------------------------------------------------------

  ------------------------  ------------------------  ------------------------
  |                      |  |                      |  |                      |
  |  Linke Spalte        |  |  Mittlere Spalte     |  |  Rechte Spalte       |
  |  * Bild              |  |  * Text              |  |  * Bild              |
  |                      |  |  * Text              |  |  * Bild              |
  |                      |  |  * Text              |  |  * Bild              |
  |                      |  |                      |  |                      |
  ------------------------  ------------------------  ------------------------

  ----------------------------------------------------------------------------
  |                                                                          |
  |  Fußzeile                                                                |
  |  * Text                                                                  |
  |                                                                          |
  ----------------------------------------------------------------------------
```

Mit einem Klick auf die Zelle, wird dann eine Liste der Elemente innerhalb der Zelle angezeigt. Über den Zurück Button kommt man wieder auf die Übersicht.

Um nur den Inhalt der gewünschten Zelle anzuzeigen, wird die DCA Option [filter](https://contao.org/de/manual/2.11/data-container-arrays.html#datensaetze-auflisten) verwendet.

Die anzuzeigende Zelle wird über einen GET Parameter übergeben.

Es ist sicher zu stellen, dass beim verschieben zwischen Zelle, die Zuweisung über einen entsprechenden onsubmit/save Callback korrigiert wird.

Im Falle eines Responsive Layouts müssen Zeilen ggf. dupliziert werden können.

@see Templates -> Aufbau und Anordnung von Inhalten -> Responsive Layout
@see Bearbeiten von Inhalten -> Aktueller Entwurf -> Speichern von Zellenzuweisungen

```
  ----------------------------------------------------------------------------
  |                                                                          |
  |  Kopfzeile                                                               |
  |  * Text                                                                  |
  |                                                                          |
  ----------------------------------------------------------------------------

                                                     (+ Zeile davor einfügen)
  ----------------------  ----------------------  ----------------------
  |                    |  |                    |  |                    |  (^)
  |  Linke Spalte      |  |  Mittlere Spalte   |  |  Rechte Spalte     |  (x)
  |  * Bild            |  |  * Text            |  |  * Bild            |  (v)
  |                    |  |  * Text            |  |  * Bild            |
  |                    |  |  * Text            |  |  * Bild            |
  |                    |  |                    |  |                    |
  ----------------------  ----------------------  ---------------------- 
                                                    (+ Zeile danach einfügen)

  ----------------------------------------------------------------------------
  |                                                                          |
  |  Fußzeile                                                                |
  |  * Text                                                                  |
  |                                                                          |
  ----------------------------------------------------------------------------
```
### Speichern von Zellenzuweisungen

Die Zuweisung welches Inhaltselement in welcher Zelle abgelegt ist, erfolgt über das Feld `cell`.
Die Speicherung erfolgt allerdings mit einem Index.
Anstelle von `cell="col1"` wird `cell="col1[1]"` gespeichert. Dies erfolgt _immer_ um eine einfache Portierung zwischen Layouts zu ermöglichen.

Notwendig wird der Index bei Layouts mit repeatable Zeilen.
Der Index repräsentiert dabei den Zeilenindex, wobei bei 1 angefangen wird zu zählen (XPath kompatibel).

Für das Wireframe aus dem vorherigen Abschnitt, währen die korrekten Zellennamen also
- header[1]
- col1[1]
- col2[1]
- col3[1]
- footer[1]

Wobei `col1[x]`, `col2[x]` und `col3[x]` höhere Indexes annehmen kann, wenn eine weitere Zeile eingefügt wird.
### Ursprünglicher Entwurf (aus Dokumentationsgründen erhalten)

```
--- Kopfzeile -------------------------------------------------------------------------------------------------------------
                                                                                            + neues Element oben einfügen

  <> Text                                                                                    [edit] [delete] [move] [add]

  Überschrift

  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eu pretium lacus. Praesent elit arcu, interdum a gravida
  ac, sagittis ut lectus. Suspendisse tempor sollicitudin nisi. Donec imperdiet tempus turpis volutpat cursus. Ut
  lobortis nisl et massa adipiscing, ac dictum nibh placerat. Duis at lacinia lectus, vel tincidunt mauris. Donec dolor
  ligula, imperdiet non justo ut, eleifend volutpat justo. Maecenas quam urna, interdum sit amet turpis a, tempus
  sagittis leo. Vestibulum id nibh sed sapien iaculis dictum. Duis nec lorem id odio dapibus scelerisque.

---------------------------------------------------------------------------------------------------------------------------

--- Linke Spalte ----------------------  --- Mittlere Spalte --------------------  --- Rechte Spalte ----------------------
        + neues Element oben einfügen             + neues Element oben einfügen             + neues Element oben einfügen

  <> Bild [edit] [delete] [move] [add]     <> Text [edit] [delete] [move] [add]      <> Bild [edit] [delete] [move] [add]

  -----------------------------------      Überschrift                               ------------------------------------    
  |\                               /|                                                |\                                /|    
  | \                             / |      Lorem ipsum dolor sit amet,               | \                              / |    
  |  \                           /  |      consectetur adipiscing elit. Morbi        |   ============================   |
  |   \                         /   |      eu pretium lacus. Praesent elit           | /                              \ |
  |    \                       /    |      arcu, interdum a gravida ac,              |/                                \|
  |     \                     /     |      sagittis ut lectus.                       ------------------------------------
  |      \                   /      |                                                                                   
  |       \                 /       |                                                                                   
  |        \               /        |      <> Text [edit] [delete] [move] [add]      <> Bild [edit] [delete] [move] [add]
  |         \             /         |                                                                                    
  |          \           /          |      Überschrift                               ------------------------------------
  |           \         /           |                                                |\                                /|
  |            \       /            |      Lorem ipsum dolor sit amet,               | \                              / |
  |             \     /             |      consectetur adipiscing elit. Morbi        |   ============================   |
  |              \   /              |      eu pretium lacus. Praesent elit           | /                              \ |
  |               \ /               |      arcu, interdum a gravida ac,              |/                                \|
  |               / \               |      sagittis ut lectus.                       ------------------------------------
  |              /   \              |                                                                                   
  |             /     \             |                                                                                   
  |            /       \            |      <> Text [edit] [delete] [move] [add]      <> Bild [edit] [delete] [move] [add]
  |           /         \           |                                                                                    
  |          /           \          |      Überschrift                               ------------------------------------
  |         /             \         |                                                |\                                /|
  |        /               \        |      Lorem ipsum dolor sit amet,               | \                              / |
  |       /                 \       |      consectetur adipiscing elit. Morbi        |   ============================   |
  |      /                   \      |      eu pretium lacus. Praesent elit           | /                              \ |
  |     /                     \     |      arcu, interdum a gravida ac,              |/                                \|
  |    /                       \    |      sagittis ut lectus.                       ------------------------------------
  |   /                         \   |                                                                                   
  |  /                           \  |                                                                                       
  | /                             \ |                                                                                       
  |/                               \|                                                                                       
  -----------------------------------                                                                                       

---------------------------------------------------------------------------------------------------------------------------

--- Fußzeile --------------------------------------------------------------------------------------------------------------
                                                                                            + neues Element oben einfügen

  <> Text                                                                                    [edit] [delete] [move] [add]

  Überschrift

  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eu pretium lacus. Praesent elit arcu, interdum a gravida
  ac, sagittis ut lectus. Suspendisse tempor sollicitudin nisi. Donec imperdiet tempus turpis volutpat cursus. Ut
  lobortis nisl et massa adipiscing, ac dictum nibh placerat. Duis at lacinia lectus, vel tincidunt mauris. Donec dolor
  ligula, imperdiet non justo ut, eleifend volutpat justo. Maecenas quam urna, interdum sit amet turpis a, tempus
  sagittis leo. Vestibulum id nibh sed sapien iaculis dictum. Duis nec lorem id odio dapibus scelerisque.

---------------------------------------------------------------------------------------------------------------------------
```
